[package]
name = "data"
version = "0.0.0"
publish = false

[dependencies]
rocket = "0.4"
serde_derive = "1.0"
serde = "1.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json", "msgpack"]
